[package]
name = "projectasiago_mish"
version = "0.1.0"

[dependencies]
projectasiago_feta = { git = "https://github.com/projectasiago/feta" }
nom = { version = "4.0.0-beta1", default-features = false }